/**
 * App color palette - ported from Android colors.xml
 */
export const colors = {
  primary_blue: '#1f3a89',
  yellow_accent: '#f1c74b',
  bg_light_blue: '#e6ecfd',
  bg_light_blue2: '#e8eeff',
  white: '#ffffff',
  text_primary: '#131313',
  text_secondary: '#6a7282',
  text_gray: '#545e64',
  text_disabled: '#d4d4d4',
  border_gray: '#d4d4d4',
  border_light: '#e3eaf2',
  status_bar_bg: '#1f3a89',
  card_bg_white: '#ffffff',
  card_bg_light: '#e8eeff',
  card_bg_yellow_tint: '#F5E6C7',
  card_bg_yellow_tint_22: '#39F1C74B',
  footer_text: '#6a7282',
  footer_active: '#1f3a89',
  date_picker_selected_bg: '#f1c74b',
  date_picker_light_bg: '#e6ecfd',
  ledger_blue: '#1f3a89',
  ledger_light_blue: '#e8eeff',
  ledger_border: '#e3eaf2',
  ledger_yellow: '#f1c74b',
  ledger_blue_border: '#1c4488',
  ledger_white_transparent: '#1AFFFFFF',
  ledger_no_data_text: '#0e172b',
  footer_border: '#f2f4f6',
  voucher_divider: '#bcc9ec',
  voucher_yellow_tint: '#38F1C74B',
  approve_green: '#39b57c',
  reject_red: '#eb2122',
  bg_page: '#fafafd',
  stock_header_bg: '#d3d3d3',
  stock_border: '#c4d4ff',
  stock_item_highlight: '#f1c74b33',
  stock_text_dark: '#0e172b',
  stock_text_label: '#354152',
} as const;

export type Colors = typeof colors;
