/**
 * App strings - ported from Android strings.xml
 */
export const strings = {
  app_name: 'DataLynkr',
  login: 'Login',
  signup: 'Sign Up',
  signup_prompt: "Don't have an account?",
  forgot_password: 'Forgot Password?',
  reset_password: 'Reset Password',
  reset_password_description: "Enter your email address and we'll send you a link to reset your password.",
  reset_password_note_label: 'Note : ',
  reset_password_note: "If the email is registered with us, you will receive a password reset link within a few minutes.",
  send_reset_link: 'Send Reset Link',
  email: 'Email',
  email_id: 'Email ID',
  email_placeholder: 'Enter your email',
  password: 'Password',
  password_placeholder: 'Enter your password',
  welcome_back: 'Welcome Back',
  footer_copyright: '© IT Catalyst Software India Pvt Ltd, 2025.',
  name: 'Name',
  name_placeholder: 'Enter your name',
  mobile_number: 'Mobile Number',
  mobile_no: 'Mobile No',
  mobile_placeholder: 'Enter your mobile number',
  create_account: 'Create Account',
  already_have_account: 'Already have an account?',
  submit: 'Submit',
  back_to_login: 'Back to Login',
  login_success: 'Login successful',
  login_error: 'Login failed. Please check your credentials.',
  signup_success: 'Signup successful. Please login.',
  forgot_password_success: 'Password reset link sent to your email.',
  ledger_book: 'Ledger Book',
  ledger_name: 'Ledger Name',
  report_name: 'Report Name',
  from_date: 'From Date',
  to_date: 'To Date',
  select: 'Select',
  no_data: 'NO DATA',
  table_data_will_appear: 'Table data will appear here after you submit.',
  opening_balance: 'Opening Balance',
  closing_balance: 'Closing Balance',
  receivable: 'Receivable',
  payable: 'Payable',
  credit_limit: 'Credit Limit',
  voucher_details: 'Voucher Details',
  voucher_type: 'Voucher Type',
  voucher_number: 'Voucher Number',
  particulars: 'Particulars',
  ledger_entries: 'Ledger Entries',
  debit: 'Debit:',
  credit: 'Credit:',
  bill_allocations: 'Bill Allocations',
  more_details: 'More Details',
  no_additional_details: 'No additional details',
  view_full_details: 'View full details',
  order_details: 'Order Details',
  buyer_details: 'Buyer Details',
  consignee_details: 'Consignee Details',
  dispatch_details: 'Dispatch Details',
  export_details: 'Export Details',
  contact_person_details: 'Contact Person Details',
  inventory_allocations: 'Inventory Allocations',
  item_total: 'Item Total',
  grand_total: 'Grand Total',
  ledger_details: 'LEDGER DETAILS',
  dle_discount: 'DLE Discount',
  round_off: 'Round Off',
  cgst: 'CGST',
  sgst: 'SGST',
  home: 'Home',
  orders: 'Orders',
  ledger: 'Ledger',
  approvals: 'Approvals',
  summary: 'Summary',
  stock_summary: 'Stock Summary',
  export: 'Export',
  pdf: 'PDF',
  excel: 'Excel',
  print: 'Print',
  back: 'Back',
  dr: 'Dr',
  cr: 'Cr',
  loading: 'Loading…',
  error: 'Error',
  ok: 'OK',
  cancel: 'Cancel',
  list_of_connections: 'List of Connections',
  connections: 'Connections',
  select_connection: 'Select Connection',
  search_connections: 'Search connections…',
  no_connections_found: 'No connections found',
  site_id: 'Site ID',
  access_type: 'Access Type',
  shared_by_owner: 'Shared By/Owner',
  tap_to_access_ledger: 'Tap to access Ledger Book',
  access_tally_data: 'Access Tally Data',
  failed_to_load_connections: 'Failed to load connections',
  unauthorized_please_login: 'Unauthorized. Please login again.',
  network_error: 'Network error. Please try again.',
  refresh: 'Refresh',
  connected: 'Connected',
  offline: 'Offline',
  logout: 'Logout',
  sales_dashboard: 'Sales Dashboard',
  place_orders: 'Place orders',
  b_commerce_place_orders: 'B-Commerce Place orders',
  order_entry: 'Order Entry',
  select_customer: 'Select Customer',
  class_label: 'Class',
  party_details: 'Details',
  select_item: 'Select Item',
  select_item_name: 'Select Item Name',
  select_customer_voucher_first: 'Select customer and voucher type first',
  select_customer_voucher_class_first: 'Select customer, voucher type and class first',
  add_details: 'Add Details',
  place_order: 'Place Order',
  edit_details: 'Edit Details',
  price_level: 'Price Level',
  sales_ledger: 'Sales Ledger',
  order_no: 'Order No',
  order_date: 'Order Date',
  place_of_supply: 'Place of Supply',
  godown: 'Godown',
  batch_no: 'Batch #',
  select_price_level: 'Select Price Level',
  select_sales_ledger: 'Select Sales Ledger',
  enter_order_no: 'Enter Order No.',
  enter_order_date: 'Enter Order Date',
  done: 'Done',
  clear: 'Clear',
  dd_mm_yy: 'dd-mm-yy',
  voucher_approvals: 'Voucher Approvals',
  cache_management: 'Cache management',
  cache_management_2: 'Data management',
  available_soon: 'Available Soon',
  // Bill Wise
  bill_wise_outstanding: 'Bill Wise Outstandings',
  due_on: 'Due on',
  overdue_days: 'Overdue Days',
  bill_ref: 'Bill Ref',
  // Overdue Bills Details modal (Order Entry)
  overdue_bills_details: 'Overdue Bills Details',
  overdue_bills_found: 'Overdue Bill(s) Found',
  overdue_bills_message: 'Customer has outstanding bills that are past their due date. Please review the details below.',
  bill_reference: 'Bill Reference',
  bill_date: 'Bill Date',
  due_date: 'Due Date',
  days_overdue: 'Days Overdue',
  total_overdue_amount: 'Total Overdue Amount',
  opening: 'Opening',
  pending: 'Pending',
  sales: 'Sales',
  choose_different_company: 'Choose Different Company',
  // Add Details (Figma 3067-64055, 3067-64383, 3067-63666)
  buyer_bill_to: 'Buyer (Bill to)',
  mailing_name: 'Mailing Name',
  address: 'Address',
  state: 'State',
  country: 'Country',
  pin_code: 'Pin code',
  gst_registration_type: 'GST Registration Type',
  gstin_uin: 'GSTIN / UIN',
  contact_person: 'Contact Person',
  phone: 'Phone',
  bill_of_landing_lr_rr_no: 'Bill of Landing / LR-RR No.',
  date: 'Date',
  date_with_colon: 'Date:',
  consignee_ship_to: 'Consignee (Ship to)',
  mode_terms_of_payment: 'Mode/Terms of payment',
  other_references: 'Other References',
  terms_of_delivery: 'Terms of Delivery',
  dispatch_through: 'Dispatch through',
  destination: 'Destination',
  carrier_name_agent: 'Carrier Name/Agent',
  place_of_receipt_by_shipper: 'Place of Receipt by Shipper',
  vessel_flight_no: 'Vessel / Flight No.',
  port_of_loading: 'Port of Loading',
  port_of_discharge: 'Port of Discharge',
  country_to: 'Country to',
  shipping_bill_no: 'Shipping Bill No.',
  port_code: 'Port Code',
  // Stock Summary screens
  stock_group_summary: 'Stock Group Summary',
  stock_item_monthly_summary: 'Stock Item Monthly Summary',
  stock_item_vouchers: 'Stock Item Vouchers',
  particulars_and_qty: 'Particulars & Qty',
  rate: 'Rate',
  value: 'Value',
  qty: 'Qty',
  inwards: 'Inwards',
  outwards: 'Outwards',
  opening_bal: 'Opening Balance',
  closing_bal: 'Closing Balance',
};

export function ledgers_available(n: number): string {
  return `${n} ledgers available`;
}

export function connections_available(n: number): string {
  return `${n} connections available`;
}
